global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@prestashop.local'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'console'

receivers:
- name: 'console'
  webhook_configs:
  - url: 'http://127.0.0.1:9093/webhook'
    send_resolved: true